# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-26 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagementApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='highlighted',
        ),
    ]
