# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-06 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagementApp', '0003_auto_20181129_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
