# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-14 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagementApp', '0004_auto_20181206_1404'),
        ('favourites', '0002_comments'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comments',
            unique_together=set([('comment', 'user_uuid')]),
        ),
    ]
